services: # define all containers/services Docker will manage
  db: # name of the service - optionally called db cause its a postgres db
    image: postgres:17.4
    container_name: fieldnotes_db
    restart: always # container auto restarts on crash or docker restart
    environment: # environment variables for the container
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERID}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports: # ports to expose
      - "8001:5432"
    volumes: # volumes to mount
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: ./Api/
    environment:
      DB_CONNECTION_STRING: 'Server=localhost;Port=5432;Database=${DB_NAME};Username=${DB_USERID};Password=${DB_PASSWORD}'
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db
    ports:
      - "5000:80"
    networks:
      - backend
  ui:
    build:
      context: ./Client/
    depends_on:
      - api
    environment:
      - API_URL=http://api:80
    ports:
      - "8080:8080"
    networks:
      - backend

volumes: # volumes to create
  pgdata:

networks:
  backend:
    driver: bridge
