services: # define all containers/services Docker will manage
  db: # name of the service - optionally called db cause its a postgres db
    image: postgres:17.4
    container_name: fieldnotes_db
    restart: always # container auto restarts on crash or docker restart
    environment: # environment variables for the container
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERID}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports: # ports to expose
      - "8001:5432"
    volumes: # volumes to mount
      - db-data:/var/lib/postgresql/data
  api:
    build: .
    environment:
      DB_CONNECTION_STRING: 'Server=localhost;Port=5432;Database=${DB_NAME};Username=${DB_USERID};Password=${DB_PASSWORD}'
    depends_on:
      - db

volumes: # volumes to create
  db-data:

