services: # define all containers/services Docker will manage
  db: # name of the service - optionally called db cause its a postgres db
    image: postgres:17.4
    container_name: fieldnotes_db
    restart: always # container auto restarts on crash or docker restart
    environment: # environment variables for the container
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: # ports to expose
      - "8001:5432"
    volumes: # volumes to mount
      - db-data:/var/lib/postgresql/data
  api:
    build: .
    environment:
      DB_CONNECTION_STRING: Host=localhost;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      - db

volumes: # volumes to create
  db-data:

